#!/bin/bash
work_dir=$(pwd)
script_dir=$(cd "$(dirname "$0")"; pwd)

# change the user name and password to yours.
username=Your_user_name
password=Your_password

# make sure the work directory is in where the script is.
cd $script_dir

# change the user name and password to yours.
username=Your_user_name
password=Your_password

echo "username=\"$username\"" > $script_dir/bin/config.sh
echo "password=\"$password\"" >> $script_dir/bin/config.sh

rm -f -r -d ./bin/ppmAuto_lib
mkdir ./bin/ppmAuto_lib
cp ./source/libs/* ./bin/ppmAuto_lib

sudo chmod 777 $script_dir/bin/run.sh
source $script_dir/bin/scheduled.sh
exit
