#!/bin/bash
work_dir=$(pwd)
script_dir=$(cd "$(dirname "$0")"; pwd)

# make sure the work directory is in where the script is.
cd $script_dir
source account.ini

echo "username=\"$username\"" > $script_dir/bin/config.ini
echo "password=\"$password\"" >> $script_dir/bin/config.ini

rm -f -r -d ./bin/ppmAuto_lib
mkdir ./bin/ppmAuto_lib
cp ./source/libs/* ./bin/ppmAuto_lib

sudo chmod 777 $script_dir/bin/run.sh
source $script_dir/bin/scheduled.sh
exit
